### CREAR tarea
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "A estudial 4 !!",
  "description": "Tarea de prueba"
}

### RECUPERAR UNA tarea
GET http://localhost:3000/tasks/fa2147fa-8f48-4663-8dd4-9ff7c200be94

### RECUPERAR TODAS las tareas
GET http://localhost:3000/tasks

### DELETE task
DELETE  http://localhost:3000/tasks/cbe83149-e530-4e17-93c0-8c59b5f6a30a