### CREAR tarea
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Explicarle a Anita",
  "description": "porque no se sabe"
}

### RECUPERAR UNA tarea
GET http://localhost:3000/tasks/6aa80565-ed8e-4d89-a1bc-f286c7b684cd

### RECUPERAR TODAS las tareas
GET http://localhost:3000/tasks

### DELETE task
DELETE  http://localhost:3000/tasks/6aa80565-ed8e-4d89-a1bc-f286c7b684cd

### UPDATE tarea
PATCH  http://localhost:3000/tasks/6aa80565-ed8e-4d89-a1bc-f286c7b684cd
Content-Type: application/json

{
  "title": "Anita se ha ido",
  "completed": true
}